# Create the temporary build container
FROM golang:1.21.5 AS builder

# Copy go source code
WORKDIR /src/
COPY . .

# Build Go executable
RUN go build -o /tmp/webapi ./cmd/webapi

# Create the final container
FROM ubuntu:23.10

# Expose ports 3000 and 8000
EXPOSE 3000

# Copy the Go executable from the builder container
WORKDIR /app/
COPY --from=builder /tmp/webapi ./

# Setup volume for uploaded images storage
VOLUME ["/app/uploads"]

# Run the Go executable
CMD ["/app/webapi"]



